name: BelaCI
on: 
  push:
    paths-ignore:
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
      - "docs/**"
      - '**.md'
      - '**.txt'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - "docs/**"
      - '**.md'
      - '**.txt'
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        target: [win64, arm64]
    steps:
      - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: compile-bela
        run: pwsh -NoProfile -NoLogo -ExecutionPolicy unrestricted -File "./build.ps1" -Target "${{ matrix.target }}"

      
